target:
  - name: "Local Target 1"
    url: "http://localhost/api/healt-check"
    ssl_verify: false
    method: "GET"
    status: 200
    headers:
      - name: "Content-Type"
        value: "application/json"
    timeout: 3
    retry:
      count: 1
      interval: 1
alert:
  - type: "telegram"
    name: "Telegram Alert Bot"
    token: "1234:AAE0J"
    chat_id: 1
  - type: "std"
    name: "STD Log"
